import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const docsRoot = resolve(__dirname, '..')
const content = (name: string): string =>
  readFileSync(resolve(docsRoot, 'content/docs', name), 'utf8')

// Docs-content guardrails: public pages exist and the generated pages carry their provenance
// markers (single-source law — they are rebuilt on every build).
describe('docs content', () => {
  it('ships the manifest hand-off guide alongside the core docs', () => {
    for (const f of [
      'index.mdx',
      'tools.mdx',
      'standard.mdx',
      'verify.mdx',
      'api.mdx',
      'x402.mdx',
      'manifest.mdx',
    ]) {
      expect(existsSync(resolve(docsRoot, 'content/docs', f)), f).toBe(true)
    }
  })
  it('tools.mdx is generated from the toolspec and lists all eleven tools', () => {
    const t = content('tools.mdx')
    expect(t).toContain('GENERATED by scripts/gen-docs.mjs')
    for (const name of [
      'asy_ats_scan',
      'asy_claim_audit',
      'asy_fit_brief',
      'asy_cover_letter',
      'asy_story_bank',
      'asy_interview_prep',
      'asy_tailor_resume',
      'asy_create_dossier_job',
      'asy_job_status',
      'asy_job_result',
      'asy_verify',
    ]) {
      expect(t).toContain(name)
    }
  })
  it('standard.mdx mirrors renderStandardMarkdown', () => {
    const s = content('standard.mdx')
    expect(s).toContain('GENERATED by scripts/gen-docs.mjs')
    expect(s).toContain('The standard does not bend for our own marketing.')
  })
})
